### ISSUE TITLE
Ajustar la creación de una o mas indicadores por actividad (nombre del indicador , formula y meta

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#137]
Se debe desarrollar el componente para que al relacionar indicador se pueda relacionados dos registros, tener presente que el formulario es dinámico, ajustar el json para que se almacene los registros  en un solo subgrupo detalle, la issue debe cumplir con los siguientes requerimientos:

- [ ] Analizar como crear un segundo indicador para el componente, definir una bandera para  la cantidad de indicadores se puedan registrar.
- [ ] Desarrollar el ajuste para los indicadores en el componente
- [ ] Ajustar la funcionalidad para almacenar los indicadores en un solo arreglo, la consulta y la actualización
