### ISSUE TITLE
Crear funcionalidad para la carga de Armonización con el PED, Armonización con el Plan Indicativo, Formula(s), Meta(s), Clasificación unidad de medida, Tendencia del indicador (OAPC), Criterio del indicador (OAPC) y registro de los nuevos campos del reporte cualitativo

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/planeacion_cliente#375]
Se debe Crear funcionalidad para la carga de Armonización con el PED, Armonización con el Plan Indicativo, Formula(s), Meta(s), Clasificación unidad de medida, Tendencia del indicador (OAPC), Criterio del indicador (OAPC) y registro de los nuevos campos del reporte cualitativo en el componente desarrollado en la issue #374, la issue debe cumplir con los siguientes requerimientos:

- [ ] Para la vista de unidad académico administrativo  realizar la funcionalidad para guardado y consulta tabla planea de acción activos, tabla listado de actividades, información del plan, componente cualitativo y componente cuantitativo.
- [ ] Para la vista de Oficina de planeación realizar la funcionalidad para la consulta de tabla unidades y tabla listado de actividades, información del plan, componente cualitativo y componente cuantitativo
- [ ] Para la vista de Oficina de planeación realizar la funcionalidad de guardado de estado de actividad
